// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/alumni/[alumniId]/media" | "/admin/invites" | "/alumni" | "/alumni/[slug]" | "/alumni/update" | "/campaign" | "/campaign/[slug]" | "/cause/[slug]" | "/directory" | "/donate" | "/donate/cancel" | "/donate/success" | "/drama-club" | "/drama-club/[slug]" | "/events" | "/events/[id]" | "/events/festivals" | "/events/fundraisers" | "/events/performances" | "/festivals/[id]" | "/font-test" | "/friends" | "/friends/ambassador" | "/friends/volunteer" | "/gatherings/[id]" | "/location/[slug]" | "/login" | "/partners" | "/partners/corporate-giving" | "/partners/propose-project" | "/partners/universities" | "/programs/[slug]" | "/projects" | "/role/[slug]" | "/season/[season]" | "/story-map" | "/story/[slug]" | "/tag/[slug]" | "/test-auth" | "/theatre" | "/theatre/[slug]" | "/theme/[slug]" | "/title/[slug]"
type AppRouteHandlerRoutes = "/api/admin/auto-canon" | "/api/admin/diag-aliases" | "/api/admin/diag-alumni" | "/api/admin/diag-canon" | "/api/admin/diag-loadcsv" | "/api/admin/diag-profile" | "/api/admin/flush-slug-aliases" | "/api/admin/forward-slug" | "/api/admin/invalidate" | "/api/admin/invites/generate" | "/api/admin/profile-owners/upsert" | "/api/admin/seed-slugs" | "/api/admin/slug-health" | "/api/alumni/community-feed" | "/api/alumni/effective/[slug]" | "/api/alumni/lookup" | "/api/alumni/media/list" | "/api/alumni/owner" | "/api/alumni/save" | "/api/alumni/tag-suggestion" | "/api/alumni/update" | "/api/alumni/update/undo" | "/api/ambassador" | "/api/auth/[...nextauth]" | "/api/campaign/[slug]/totals" | "/api/contact" | "/api/debug/public" | "/api/debug/slug-forward" | "/api/drama-club-updates" | "/api/events/[id]/ics" | "/api/health" | "/api/healthz" | "/api/img" | "/api/mailing-list" | "/api/map/append-story" | "/api/map/my-stories" | "/api/map/story" | "/api/map/write-story" | "/api/media/feature" | "/api/media/list" | "/api/media/thumb" | "/api/media/thumb/[fileId]" | "/api/namestack-hint" | "/api/partner-proposal" | "/api/profiles/live" | "/api/profiles/resolve" | "/api/stories" | "/api/stories/by-key" | "/api/stripe/checkout" | "/api/stripe/session" | "/api/stripe/webhook" | "/api/upload" | "/api/volunteer" | "/media/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/drama-club" | "/story/[slug]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/alumni/[alumniId]/media": { "alumniId": string; }
  "/admin/invites": {}
  "/alumni": {}
  "/alumni/[slug]": { "slug": string; }
  "/alumni/update": {}
  "/api/admin/auto-canon": {}
  "/api/admin/diag-aliases": {}
  "/api/admin/diag-alumni": {}
  "/api/admin/diag-canon": {}
  "/api/admin/diag-loadcsv": {}
  "/api/admin/diag-profile": {}
  "/api/admin/flush-slug-aliases": {}
  "/api/admin/forward-slug": {}
  "/api/admin/invalidate": {}
  "/api/admin/invites/generate": {}
  "/api/admin/profile-owners/upsert": {}
  "/api/admin/seed-slugs": {}
  "/api/admin/slug-health": {}
  "/api/alumni/community-feed": {}
  "/api/alumni/effective/[slug]": { "slug": string; }
  "/api/alumni/lookup": {}
  "/api/alumni/media/list": {}
  "/api/alumni/owner": {}
  "/api/alumni/save": {}
  "/api/alumni/tag-suggestion": {}
  "/api/alumni/update": {}
  "/api/alumni/update/undo": {}
  "/api/ambassador": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/campaign/[slug]/totals": { "slug": string; }
  "/api/contact": {}
  "/api/debug/public": {}
  "/api/debug/slug-forward": {}
  "/api/drama-club-updates": {}
  "/api/events/[id]/ics": { "id": string; }
  "/api/health": {}
  "/api/healthz": {}
  "/api/img": {}
  "/api/mailing-list": {}
  "/api/map/append-story": {}
  "/api/map/my-stories": {}
  "/api/map/story": {}
  "/api/map/write-story": {}
  "/api/media/feature": {}
  "/api/media/list": {}
  "/api/media/thumb": {}
  "/api/media/thumb/[fileId]": { "fileId": string; }
  "/api/namestack-hint": {}
  "/api/partner-proposal": {}
  "/api/profiles/live": {}
  "/api/profiles/resolve": {}
  "/api/stories": {}
  "/api/stories/by-key": {}
  "/api/stripe/checkout": {}
  "/api/stripe/session": {}
  "/api/stripe/webhook": {}
  "/api/upload": {}
  "/api/volunteer": {}
  "/campaign": {}
  "/campaign/[slug]": { "slug": string; }
  "/cause/[slug]": { "slug": string; }
  "/directory": {}
  "/donate": {}
  "/donate/cancel": {}
  "/donate/success": {}
  "/drama-club": {}
  "/drama-club/[slug]": { "slug": string; }
  "/events": {}
  "/events/[id]": { "id": string; }
  "/events/festivals": {}
  "/events/fundraisers": {}
  "/events/performances": {}
  "/festivals/[id]": { "id": string; }
  "/font-test": {}
  "/friends": {}
  "/friends/ambassador": {}
  "/friends/volunteer": {}
  "/gatherings/[id]": { "id": string; }
  "/location/[slug]": { "slug": string; }
  "/login": {}
  "/media/[id]": { "id": string; }
  "/partners": {}
  "/partners/corporate-giving": {}
  "/partners/propose-project": {}
  "/partners/universities": {}
  "/programs/[slug]": { "slug": string; }
  "/projects": {}
  "/role/[slug]": { "slug": string; }
  "/season/[season]": { "season": string; }
  "/story-map": {}
  "/story/[slug]": { "slug": string; }
  "/tag/[slug]": { "slug": string; }
  "/test-auth": {}
  "/theatre": {}
  "/theatre/[slug]": { "slug": string; }
  "/theme/[slug]": { "slug": string; }
  "/title/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/drama-club": never
  "/story/[slug]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
