// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/alumni/[alumniId]/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/alumni/[alumniId]/media">> = Specific
  const handler = {} as typeof import("../../../app/admin/alumni/[alumniId]/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/invites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invites">> = Specific
  const handler = {} as typeof import("../../../app/admin/invites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/alumni/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/alumni/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/alumni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni">> = Specific
  const handler = {} as typeof import("../../../app/alumni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/alumni/update/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/update">> = Specific
  const handler = {} as typeof import("../../../app/alumni/update/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/campaign/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaign/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/campaign/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/campaign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaign">> = Specific
  const handler = {} as typeof import("../../../app/campaign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cause/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cause/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/cause/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/directory">> = Specific
  const handler = {} as typeof import("../../../app/directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/donate/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/donate/cancel">> = Specific
  const handler = {} as typeof import("../../../app/donate/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/donate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/donate">> = Specific
  const handler = {} as typeof import("../../../app/donate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/donate/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/donate/success">> = Specific
  const handler = {} as typeof import("../../../app/donate/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/drama-club/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drama-club/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/drama-club/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/drama-club/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drama-club">> = Specific
  const handler = {} as typeof import("../../../app/drama-club/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]">> = Specific
  const handler = {} as typeof import("../../../app/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/events/festivals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/festivals">> = Specific
  const handler = {} as typeof import("../../../app/events/festivals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/events/fundraisers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/fundraisers">> = Specific
  const handler = {} as typeof import("../../../app/events/fundraisers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../../app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/events/performances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/performances">> = Specific
  const handler = {} as typeof import("../../../app/events/performances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/festivals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/festivals/[id]">> = Specific
  const handler = {} as typeof import("../../../app/festivals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/font-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/font-test">> = Specific
  const handler = {} as typeof import("../../../app/font-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/friends/ambassador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/friends/ambassador">> = Specific
  const handler = {} as typeof import("../../../app/friends/ambassador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/friends/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/friends">> = Specific
  const handler = {} as typeof import("../../../app/friends/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/friends/volunteer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/friends/volunteer">> = Specific
  const handler = {} as typeof import("../../../app/friends/volunteer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/gatherings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gatherings/[id]">> = Specific
  const handler = {} as typeof import("../../../app/gatherings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/location/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/location/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/location/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partners/corporate-giving/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/corporate-giving">> = Specific
  const handler = {} as typeof import("../../../app/partners/corporate-giving/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../../app/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partners/propose-project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/propose-project">> = Specific
  const handler = {} as typeof import("../../../app/partners/propose-project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partners/universities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/universities">> = Specific
  const handler = {} as typeof import("../../../app/partners/universities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/programs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/programs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/role/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/role/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/role/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/season/[season]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/season/[season]">> = Specific
  const handler = {} as typeof import("../../../app/season/[season]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/story-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/story-map">> = Specific
  const handler = {} as typeof import("../../../app/story-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/story/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/story/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/story/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tag/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tag/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/tag/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-auth">> = Specific
  const handler = {} as typeof import("../../../app/test-auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/theatre/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/theatre/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/theatre/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/theatre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/theatre">> = Specific
  const handler = {} as typeof import("../../../app/theatre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/theme/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/theme/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/theme/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/title/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/title/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/title/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/auto-canon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auto-canon">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/auto-canon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/diag-aliases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diag-aliases">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/diag-aliases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/diag-alumni/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diag-alumni">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/diag-alumni/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/diag-canon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diag-canon">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/diag-canon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/diag-loadcsv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diag-loadcsv">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/diag-loadcsv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/diag-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diag-profile">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/diag-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/flush-slug-aliases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/flush-slug-aliases">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/flush-slug-aliases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/forward-slug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/forward-slug">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/forward-slug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/invalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invalidate">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/invalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/invites/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invites/generate">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/invites/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/profile-owners/upsert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/profile-owners/upsert">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/profile-owners/upsert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/seed-slugs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/seed-slugs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/seed-slugs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/slug-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/slug-health">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/slug-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/community-feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/community-feed">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/community-feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/effective/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/effective/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/effective/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/lookup">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/media/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/media/list">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/media/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/owner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/owner">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/owner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/save">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/tag-suggestion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/tag-suggestion">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/tag-suggestion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/update">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alumni/update/undo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/update/undo">> = Specific
  const handler = {} as typeof import("../../../app/api/alumni/update/undo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ambassador/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ambassador">> = Specific
  const handler = {} as typeof import("../../../app/api/ambassador/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/campaign/[slug]/totals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaign/[slug]/totals">> = Specific
  const handler = {} as typeof import("../../../app/api/campaign/[slug]/totals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/public">> = Specific
  const handler = {} as typeof import("../../../app/api/debug/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug/slug-forward/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/slug-forward">> = Specific
  const handler = {} as typeof import("../../../app/api/debug/slug-forward/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/drama-club-updates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drama-club-updates">> = Specific
  const handler = {} as typeof import("../../../app/api/drama-club-updates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/events/[id]/ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/ics">> = Specific
  const handler = {} as typeof import("../../../app/api/events/[id]/ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/healthz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/healthz">> = Specific
  const handler = {} as typeof import("../../../app/api/healthz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/img/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/img">> = Specific
  const handler = {} as typeof import("../../../app/api/img/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mailing-list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mailing-list">> = Specific
  const handler = {} as typeof import("../../../app/api/mailing-list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/map/append-story/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/map/append-story">> = Specific
  const handler = {} as typeof import("../../../app/api/map/append-story/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/map/my-stories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/map/my-stories">> = Specific
  const handler = {} as typeof import("../../../app/api/map/my-stories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/map/story/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/map/story">> = Specific
  const handler = {} as typeof import("../../../app/api/map/story/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/map/write-story/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/map/write-story">> = Specific
  const handler = {} as typeof import("../../../app/api/map/write-story/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/media/feature/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/feature">> = Specific
  const handler = {} as typeof import("../../../app/api/media/feature/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/media/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/list">> = Specific
  const handler = {} as typeof import("../../../app/api/media/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/media/thumb/[fileId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/thumb/[fileId]">> = Specific
  const handler = {} as typeof import("../../../app/api/media/thumb/[fileId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/media/thumb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/thumb">> = Specific
  const handler = {} as typeof import("../../../app/api/media/thumb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/namestack-hint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/namestack-hint">> = Specific
  const handler = {} as typeof import("../../../app/api/namestack-hint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/partner-proposal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner-proposal">> = Specific
  const handler = {} as typeof import("../../../app/api/partner-proposal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/profiles/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/live">> = Specific
  const handler = {} as typeof import("../../../app/api/profiles/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/profiles/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/resolve">> = Specific
  const handler = {} as typeof import("../../../app/api/profiles/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stories/by-key/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories/by-key">> = Specific
  const handler = {} as typeof import("../../../app/api/stories/by-key/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories">> = Specific
  const handler = {} as typeof import("../../../app/api/stories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stripe/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/session">> = Specific
  const handler = {} as typeof import("../../../app/api/stripe/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../../app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/volunteer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/volunteer">> = Specific
  const handler = {} as typeof import("../../../app/api/volunteer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/media/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/media/[id]">> = Specific
  const handler = {} as typeof import("../../../app/media/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/drama-club/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/drama-club">> = Specific
  const handler = {} as typeof import("../../../app/drama-club/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/story/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/story/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/story/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
